models:
  random_forest:
    model_type: RandomForest
    params:
      max_depth: 10
      min_samples_leaf: 1
      min_samples_split: 2
      n_estimators:  200
      random_state: 42

  xgboost:
    model_type: XGBoost
    params:
      colsample_bytree: 0.7
      learning_rate: 0.1
      max_depth: 3
      n_estimators: 300
      subsample: 0.5
      random_state: 42
      objective: 'reg:squarederror'

features:
  - Date
  - main.temp
  - main.feels_like
  - main.temp_min
  - main.temp_max
  - main.humidity
  - wind.speed

target: main.temp

paths:
  processed_path_data: '/Users/kaduangelucci/Documents/Estudos/weather_prediction/src/data/processed/consolidado.csv'
  prediction_path_data: '/Users/kaduangelucci/Documents/Estudos/weather_prediction/src/data/processed/predictions.csv'