models:
  random_forest:
    model_type: RandomForest
    params:
      n_estimators: 100
      max_depth: 10
      random_state: 42

  xgboost:
    model_type: XGBoost
    params:
      n_estimators: 100
      max_depth: 10
      learning_rate: 0.1
      random_state: 42
      objective: 'reg:squarederror'
